# branch 'master'
[context.production]
  command = "echo 'production/master'"
  environment = { MY_ENV = "production" }

# branch 'staging'
[context.staging]
  command = "echo 'staging'"
  environment = { MY_ENV = "staging" }