# branch 'master'
[context.production]
  command = "npm run build:netlify"
  environment = { MY_ENV = "production" }

# branch 'staging'
[context.staging]
  command = "npm run build:netlify"
  environment = { MY_ENV = "staging", REMOTE_DATABASE = "schocken-remote-staging" }