# branch 'master'
[context.production]
  command = "echo 'production/master' && npm run build:netlify"
  environment = { MY_ENV = "production" }

# branch 'staging'
[context.staging]
  command = "echo 'staging' && npm run build:netlify"
  environment = { MY_ENV = "staging" }