export enum WorkerActions {
  COUNT_EVENT_TYPE_BY_ID = 'COUNT_EVENT_TYPE_BY_ID',
  COUNT_GAMES = 'COUNT_GAMES',
  COUNT_ROUNDS = 'COUNT_ROUNDS',
  GET_MAX_ROUND_COUNT = 'GET_MAX_ROUND_COUNT',
  GET_ATTENDANCE_COUNT = 'GET_ATTENDANCE_COUNT',
  GET_SCHOCK_AUS_STREAK = 'GET_SCHOCK_AUS_STREAK',
  GET_MAX_SCHOCK_AUS_BY_PLAYER = 'GET_MAX_SCHOCK_AUS_BY_PLAYER',
  GET_LOSE_RATES = 'GET_LOSE_RATES'
}
